#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=https://+:8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["BuildingConstructApi/BuildingConstructApi.csproj", "BuildingConstructApi/"]
COPY ["BuildingConstructApplication/Application.csproj", "BuildingConstructApplication/"]
COPY ["ViewModels/ViewModels.csproj", "ViewModels/"]
COPY ["Data/Data.csproj", "Data/"]
COPY ["Constants/Constants.csproj", "Constants/"]

RUN dotnet restore "BuildingConstructApi/BuildingConstructApi.csproj"
COPY . .
WORKDIR "/src/BuildingConstructApi"
RUN dotnet build "BuildingConstructApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BuildingConstructApi.csproj" -c Release -o /app/publish /p:UseAppHost=false


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BuildingConstructApi.dll"]