// <auto-generated />
using System;
using Data.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(BuildingConstructDbContext))]
    [Migration("20221230052130_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Entities.AppliedPost", b =>
                {
                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<int>("BuilderID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PostID", "BuilderID");

                    b.HasIndex("BuilderID");

                    b.HasIndex("GroupID");

                    b.ToTable("AppliedPost", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Builder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Place")
                        .HasColumnType("int");

                    b.Property<Guid?>("TypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeID");

                    b.ToTable("Builders");
                });

            modelBuilder.Entity("Data.Entities.BuilderPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuilderID")
                        .HasColumnType("int");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int>("PostCategories")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuilderID");

                    b.ToTable("BuilderPosts");
                });

            modelBuilder.Entity("Data.Entities.BuilderPostSkill", b =>
                {
                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("BuilderPostID")
                        .HasColumnType("int");

                    b.HasKey("SkillID", "BuilderPostID");

                    b.HasIndex("BuilderPostID");

                    b.ToTable("BuilderPostSkill", (string)null);
                });

            modelBuilder.Entity("Data.Entities.BuilderPostType", b =>
                {
                    b.Property<Guid>("TypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BuilderPostID")
                        .HasColumnType("int");

                    b.HasKey("TypeID", "BuilderPostID");

                    b.HasIndex("BuilderPostID");

                    b.ToTable("BuilderPostType", (string)null);
                });

            modelBuilder.Entity("Data.Entities.BuilderSkill", b =>
                {
                    b.Property<int>("BuilderSkillID")
                        .HasColumnType("int");

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.HasKey("BuilderSkillID", "SkillID");

                    b.HasIndex("SkillID");

                    b.ToTable("BuilderSkills", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Categories", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Data.Entities.Commitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OptionalTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salaries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Commitment", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contractors", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ContractorPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContractorID")
                        .HasColumnType("int");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("NumberPeople")
                        .HasColumnType("int");

                    b.Property<int>("PeopeRemained")
                        .HasColumnType("int");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int>("PostCategories")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salaries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StarDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractorID");

                    b.ToTable("ContractorPosts", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ContractorPostProduct", b =>
                {
                    b.Property<int>("ProductSystemID")
                        .HasColumnType("int");

                    b.Property<int>("ContractorPostID")
                        .HasColumnType("int");

                    b.HasKey("ProductSystemID", "ContractorPostID");

                    b.HasIndex("ContractorPostID");

                    b.ToTable("ContractorPostProduct", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ContractorPostSkill", b =>
                {
                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("ContractorPostID")
                        .HasColumnType("int");

                    b.HasKey("SkillID", "ContractorPostID");

                    b.HasIndex("ContractorPostID");

                    b.ToTable("ContractorPostSkills", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ContractorPostType", b =>
                {
                    b.Property<Guid>("TypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContractorPostID")
                        .HasColumnType("int");

                    b.HasKey("TypeID", "ContractorPostID");

                    b.HasIndex("ContractorPostID");

                    b.ToTable("ContractorPostType", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BuilderID")
                        .HasColumnType("int");

                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuilderID");

                    b.ToTable("Group", (string)null);
                });

            modelBuilder.Entity("Data.Entities.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TypeID");

                    b.ToTable("GroupMember", (string)null);
                });

            modelBuilder.Entity("Data.Entities.MaterialStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialStores", (string)null);
                });

            modelBuilder.Entity("Data.Entities.PostCommitment", b =>
                {
                    b.Property<int>("PostID")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CommitmentID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<bool>("IsAuthor")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PostID", "UserID", "CommitmentID");

                    b.HasIndex("CommitmentID");

                    b.HasIndex("GroupID");

                    b.HasIndex("UserID");

                    b.ToTable("PostCommitment", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ProductCategories", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "CategoriesID");

                    b.HasIndex("CategoriesID");

                    b.ToTable("ProductCategories", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialStoreID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldQuantities")
                        .HasColumnType("int");

                    b.Property<int>("UnitInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialStoreID");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ProductSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FromSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductSystems", (string)null);
                });

            modelBuilder.Entity("Data.Entities.ProductSystemCategories", b =>
                {
                    b.Property<int>("ProductSystemID")
                        .HasColumnType("int");

                    b.Property<int>("CategoriesID")
                        .HasColumnType("int");

                    b.HasKey("ProductSystemID", "CategoriesID");

                    b.HasIndex("CategoriesID");

                    b.ToTable("ProductSystemCategories", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("FromSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types", (string)null);
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuilderId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContractorId")
                        .HasColumnType("int");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaterialStoreID")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VerifyID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuilderId")
                        .IsUnique()
                        .HasFilter("[BuilderId] IS NOT NULL");

                    b.HasIndex("ContractorId")
                        .IsUnique()
                        .HasFilter("[ContractorId] IS NOT NULL");

                    b.HasIndex("MaterialStoreID")
                        .IsUnique()
                        .HasFilter("[MaterialStoreID] IS NOT NULL");

                    b.HasIndex("VerifyID")
                        .IsUnique()
                        .HasFilter("[VerifyID] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Verify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BackID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FaceImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.ToTable("Verifies", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.AppliedPost", b =>
                {
                    b.HasOne("Data.Entities.Builder", "Builder")
                        .WithMany("AppliedPosts")
                        .HasForeignKey("BuilderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Group", "Group")
                        .WithMany("AppliedPosts")
                        .HasForeignKey("GroupID");

                    b.HasOne("Data.Entities.ContractorPost", "ContractorPosts")
                        .WithMany("AppliedPosts")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");

                    b.Navigation("ContractorPosts");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Data.Entities.Builder", b =>
                {
                    b.HasOne("Data.Entities.Type", "Type")
                        .WithMany("Builder")
                        .HasForeignKey("TypeID");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Data.Entities.BuilderPost", b =>
                {
                    b.HasOne("Data.Entities.Builder", "Builder")
                        .WithMany("Posts")
                        .HasForeignKey("BuilderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");
                });

            modelBuilder.Entity("Data.Entities.BuilderPostSkill", b =>
                {
                    b.HasOne("Data.Entities.BuilderPost", "BuilderPost")
                        .WithMany("BuilderPostSkills")
                        .HasForeignKey("BuilderPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Skill", "Skills")
                        .WithMany("BuilderPostSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuilderPost");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Data.Entities.BuilderPostType", b =>
                {
                    b.HasOne("Data.Entities.BuilderPost", "BuilderPosts")
                        .WithMany("BuilderPostTypes")
                        .HasForeignKey("BuilderPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Type", "Types")
                        .WithMany("BuilderPostTypes")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuilderPosts");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("Data.Entities.BuilderSkill", b =>
                {
                    b.HasOne("Data.Entities.Builder", "Builder")
                        .WithMany("BuilderSkills")
                        .HasForeignKey("BuilderSkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Skill", "Skill")
                        .WithMany("BuilderSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Builder");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Data.Entities.ContractorPost", b =>
                {
                    b.HasOne("Data.Entities.Contractor", "Contractor")
                        .WithMany("ContractorPosts")
                        .HasForeignKey("ContractorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contractor");
                });

            modelBuilder.Entity("Data.Entities.ContractorPostProduct", b =>
                {
                    b.HasOne("Data.Entities.ContractorPost", "ContractorPost")
                        .WithMany("ContractorPostProducts")
                        .HasForeignKey("ContractorPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ProductSystem", "ProductSystem")
                        .WithMany("ContractorPostProducts")
                        .HasForeignKey("ProductSystemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractorPost");

                    b.Navigation("ProductSystem");
                });

            modelBuilder.Entity("Data.Entities.ContractorPostSkill", b =>
                {
                    b.HasOne("Data.Entities.ContractorPost", "ContractorPost")
                        .WithMany("PostSkills")
                        .HasForeignKey("ContractorPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Skill", "Skills")
                        .WithMany("ContractorPostSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractorPost");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Data.Entities.ContractorPostType", b =>
                {
                    b.HasOne("Data.Entities.ContractorPost", "ContractorPost")
                        .WithMany("ContractorPostTypes")
                        .HasForeignKey("ContractorPostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Type", "Type")
                        .WithMany("ContractorPostTypes")
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContractorPost");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Data.Entities.Group", b =>
                {
                    b.HasOne("Data.Entities.Builder", "Builder")
                        .WithMany("Groups")
                        .HasForeignKey("BuilderID");

                    b.Navigation("Builder");
                });

            modelBuilder.Entity("Data.Entities.GroupMember", b =>
                {
                    b.HasOne("Data.Entities.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId");

                    b.HasOne("Data.Entities.Type", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Data.Entities.PostCommitment", b =>
                {
                    b.HasOne("Data.Entities.Commitment", "Commitment")
                        .WithMany("PostCommitments")
                        .HasForeignKey("CommitmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Group", "Group")
                        .WithMany("PostCommitments")
                        .HasForeignKey("GroupID");

                    b.HasOne("Data.Entities.ContractorPost", "ContractorPosts")
                        .WithMany("PostCommitments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.User", "User")
                        .WithMany("PostCommitments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("ContractorPosts");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.ProductCategories", b =>
                {
                    b.HasOne("Data.Entities.Categories", "Categories")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Products", "Products")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Data.Entities.Products", b =>
                {
                    b.HasOne("Data.Entities.MaterialStore", "MaterialStore")
                        .WithMany("Products")
                        .HasForeignKey("MaterialStoreID");

                    b.Navigation("MaterialStore");
                });

            modelBuilder.Entity("Data.Entities.ProductSystemCategories", b =>
                {
                    b.HasOne("Data.Entities.Categories", "Categories")
                        .WithMany("ProductSystemCategories")
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ProductSystem", "ProductSystem")
                        .WithMany("ProductSystemCategories")
                        .HasForeignKey("ProductSystemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");

                    b.Navigation("ProductSystem");
                });

            modelBuilder.Entity("Data.Entities.Skill", b =>
                {
                    b.HasOne("Data.Entities.Type", "Type")
                        .WithMany("Skill")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.HasOne("Data.Entities.Builder", "Builder")
                        .WithOne("User")
                        .HasForeignKey("Data.Entities.User", "BuilderId");

                    b.HasOne("Data.Entities.Contractor", "Contractor")
                        .WithOne("User")
                        .HasForeignKey("Data.Entities.User", "ContractorId");

                    b.HasOne("Data.Entities.MaterialStore", "MaterialStore")
                        .WithOne("User")
                        .HasForeignKey("Data.Entities.User", "MaterialStoreID");

                    b.HasOne("Data.Entities.Verify", "Verify")
                        .WithOne("User")
                        .HasForeignKey("Data.Entities.User", "VerifyID");

                    b.Navigation("Builder");

                    b.Navigation("Contractor");

                    b.Navigation("MaterialStore");

                    b.Navigation("Verify");
                });

            modelBuilder.Entity("Data.Entities.Builder", b =>
                {
                    b.Navigation("AppliedPosts");

                    b.Navigation("BuilderSkills");

                    b.Navigation("Groups");

                    b.Navigation("Posts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.BuilderPost", b =>
                {
                    b.Navigation("BuilderPostSkills");

                    b.Navigation("BuilderPostTypes");
                });

            modelBuilder.Entity("Data.Entities.Categories", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("ProductSystemCategories");
                });

            modelBuilder.Entity("Data.Entities.Commitment", b =>
                {
                    b.Navigation("PostCommitments");
                });

            modelBuilder.Entity("Data.Entities.Contractor", b =>
                {
                    b.Navigation("ContractorPosts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.ContractorPost", b =>
                {
                    b.Navigation("AppliedPosts");

                    b.Navigation("ContractorPostProducts");

                    b.Navigation("ContractorPostTypes");

                    b.Navigation("PostCommitments");

                    b.Navigation("PostSkills");
                });

            modelBuilder.Entity("Data.Entities.Group", b =>
                {
                    b.Navigation("AppliedPosts");

                    b.Navigation("GroupMembers");

                    b.Navigation("PostCommitments");
                });

            modelBuilder.Entity("Data.Entities.MaterialStore", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.Products", b =>
                {
                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("Data.Entities.ProductSystem", b =>
                {
                    b.Navigation("ContractorPostProducts");

                    b.Navigation("ProductSystemCategories");
                });

            modelBuilder.Entity("Data.Entities.Skill", b =>
                {
                    b.Navigation("BuilderPostSkills");

                    b.Navigation("BuilderSkills");

                    b.Navigation("ContractorPostSkills");
                });

            modelBuilder.Entity("Data.Entities.Type", b =>
                {
                    b.Navigation("Builder");

                    b.Navigation("BuilderPostTypes");

                    b.Navigation("ContractorPostTypes");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Navigation("PostCommitments");
                });

            modelBuilder.Entity("Data.Entities.Verify", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
